### ISSUE TITLE
Epic plaatsen in het huidige project

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/choices-choices-the-tech-stack#7]
Kopieer de epic waar jij aan gaat werken naar de Readme van de geforkte repository en zet er een screenshot van de huidige site bij. Dit is precies wat jij gaat ontwerpen, maken en testen.

**Comment by SamaraFellaDina** [comment]
# Epic

Ontwikkel een detail pagina van een automatische toegankelijkheid scan voor de AccessDash web applicatie. Op deze pagina zijn meerdere inzichten in te zien. Zoals de totaalscore van de toegankelijkheid van de pagina en de verschillende soorten errors op de pagina.

**Comment by SamaraFellaDina** [comment]
# Stories

<img src="https://github.com/user-attachments/assets/ec55efa2-7813-40c6-a731-d3b36bab8fd1" width="400px" height="400px">
<img src="https://github.com/user-attachments/assets/b23810ce-6fb6-458d-96f7-f09abfd961d9" width="400px" height="400px">

* [ ] Maak een detail pagina van een automatische toegankelijheidsscan.
* [ ] De pagina's stijlen volgens de stijl van Accesdash
* [ ] De verschillende soorten foutmeldingen kunnen zien van de scan
* [ ]

**Comment by SamaraFellaDina** [comment]
* [ ] Maken van een `Readme.md`
